name: DSO Loadout (Branch)
run-name: ${{ github.actor }} is building a Branch! 🚀
on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  Date:
    runs-on: ubuntu-latest
    outputs:
      Date: ${{ steps.date.outputs.date }}
    steps:
      - name: Get current date
        id: DATE
        run: |
          echo "DATE=$(date '+%Y%m%d-%H%M')" >> $GITHUB_OUTPUT
          echo -e "\n$GITHUB_OUTPUT\n"
          cat $GITHUB_OUTPUT

  Code:
    needs: [Date]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v7
        with:
          submodules: true
          lfs: true

      - name: Setup Git
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"

      - name: Bundle code base for ${{ vars.COLLECTOR }}
        run: |
          git bundle create --progress ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.bundle --all
          echo -e "\nDirectory Listing\n$(ls -1sht *)"

      - name: Generate Bundle Hash
        run: |
          sha256sum -b ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.bundle | tee \
            ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.bundle.sha

      - name: Upload bundle and hash
        uses: actions/upload-artifact@v7
        with:
          name: ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.bundle
          path: ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.bundle*
          if-no-files-found: error

  Zip:
    needs: [Date]
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
  
    steps:
      - name: Check out repository code
        uses: actions/checkout@v7

      - name: Setup Git
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"

      - name: Zip code base for ${{ vars.COLLECTOR }}
        run: |
          echo -e "\nZip Files"
          zip -jD ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.zip *
          echo -e "\nList Files"
          ls -lht *

      - name: Upload Zip
        uses: actions/upload-artifact@v7
        with:
          name: ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.zip
          path: ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.zip
          if-no-files-found: error

  MakeISO:
    runs-on: ubuntu-latest
    needs: [Date, Code, Zip]
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@v7

      - name: Install mkisofs
        run: |
          sudo apt-get update -y
          sudo apt-get install -y mkisofs isomd5sum

      - name: Download Artifacts
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true

      - name: Show Artifacts
        run: ls -lh *

      - name: Generate Artifact Hash File
        run: |
          sha256sum -b * | tee \
            ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.sha

      - name: Upload Artifact Hash File
        uses: actions/upload-artifact@v7
        with:
          name: ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.sha
          path: ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.sha
          if-no-files-found: error

      - name: Make ISO
        run: |
          mkisofs -J -R -v -T -l \
            -V '${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}' \
            -A '${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}' \
            -o ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.iso \
            .

      - name: Implant MD5 sum into iso
        run: implantisomd5 ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.iso

      - name: Generate ISO Hash
        run: |
          sha256sum -b ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.iso | tee \
            ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.iso.sha

      - name: Show ISO & Hash
        run: ls -1Ssh *.iso*

      - name: Upload ISO, ToC, and hash
        uses: actions/upload-artifact@v7
        with:
          name: ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.iso
          path: ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.iso
          if-no-files-found: error

      - name: Upload ISO Hash
        uses: actions/upload-artifact@v7
        with:
          name: ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.iso.sha
          path: ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.iso.sha
          if-no-files-found: error

  Release:
    runs-on: ubuntu-latest
    needs: [Date, MakeISO]
    permissions:
      contents: write
      pull-requests: read
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v7

      - name: Download Artifacts
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true
          path: ${{ vars.COLLECTOR }}

      - name: Show Artifacts
        run: ls -1sh ${{ vars.COLLECTOR }}

      # Create Release

      # Sharepoint Upload
  Sharepoint:
    runs-on: ubuntu-latest
    needs: [Date, MakeISO]
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true

      - name: Show Artifacts
        run: ls -lh ${{ vars.COLLECTOR }}-*.*
